backend:
  name: github
  repo: Anduinmas/Anduinmas.github-io
  branch: source
  base_url: https://anduinmas-github-io-yi9u.vercel.app
  auth_endpoint: api/auth
  squash_merges: true
  open_authoring: false

media_folder: "source/images"
public_folder: "/images"
site_url: https://anduinmas.top
display_url: https://anduinmas.top
logo_url: https://anduinmas.top/images/loading.svg

locale: zh_Hans

collections:
  - name: "post"
    label: "文章"
    label_singular: "一篇文章"
    folder: "source/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "标题", name: "title", widget: "string", required: true}
      - {label: "发布日期", name: "date", widget: "datetime", required: true}
      - {label: "修改日期", name: "updated", widget: "datetime", required: false}
      - {label: "分类", name: "categories", widget: "select", multiple: true, options: ["技术", "生活", "读书", "职场", "副业"], required: true}
      - {label: "标签", name: "tags", widget: "list", required: false, default: ["随笔"]}
      - {label: "摘要", name: "description", widget: "string", required: false}
      - {label: "封面图", name: "cover", widget: "image", required: false}
      - {label: "顶部大图", name: "top_img", widget: "image", required: false}
      - {label: "关键词", name: "keywords", widget: "string", required: false}
      - {label: "置顶", name: "sticky", widget: "number", default: 0, value_type: "int", min: 0, max: 100}
      - {label: "正文", name: "body", widget: "markdown", required: true}

  - name: "pages"
    label: "页面"
    files:
      - label: "关于页"
        name: "about"
        file: "source/about/index.md"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "日期", name: "date", widget: "datetime"}
          - {label: "内容", name: "body", widget: "markdown", required: false}
      - label: "留言板"
        name: "message"
        file: "source/message/index.md"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "日期", name: "date", widget: "datetime"}
          - {label: "内容", name: "body", widget: "markdown", required: false}
      - label: "友链"
        name: "links"
        file: "source/links/index.md"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "日期", name: "date", widget: "datetime"}
          - {label: "内容", name: "body", widget: "markdown", required: false}

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
